### ISSUE TITLE
Forking.php Errors

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2264] opened 2016-09-12 23:29 UTC
Following update in DEV.  Can't get TMUX to start.  Here is the error, over and over and over.

Commit
https://github.com/nZEDb/nZEDb/commit/06e0f89046f6a5fc2685380b04f36c3af3a96ab0

[12-Sep-2016 18:22:05 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/libraries/Forking.php on line 631
[12-Sep-2016 18:22:05 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/libraries/Forking.php on line 557
[12-Sep-2016 18:22:05 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/libraries/Forking.php on line 312
[12-Sep-2016 18:22:06 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/libraries/Forking.php on line 692
[12-Sep-2016 18:22:18 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/libraries/Forking.php on line 429
[12-Sep-2016 18:22:26 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/libraries/Forking.php on line 312
[12-Sep-2016 18:22:26 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/libraries/Forking.php on line 557
[12-Sep-2016 18:22:26 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/libraries/Forking.php on line 631

**Comment by dilbaggins** [comment] 2016-09-13 00:18
+1

**Comment by dilbaggins** [comment] 2016-09-13 13:43
anything?  @niel and team? this ones affecting any and all calls to db right now.

**Comment by niel** [comment] 2016-09-13 16:47
I'm actually looking at this now.

**Comment by niel** [comment] 2016-09-13 16:54
I just pushed a commit to dev. Please update and let me know if it fixes the problem.

**Comment by dilbaggins** [comment] 2016-09-13 17:00
getting another issue see below

![image](https://cloud.githubusercontent.com/assets/3989347/18483411/e7b6de88-79b1-11e6-991b-92d8f9b915bc.png)

**Comment by scottia** [comment] 2016-09-13 17:00
No go.  Here is the revised Log error 

[13-Sep-2016 11:56:43 America/Chicago] PHP Fatal error:  Cannot redeclare nzedb\libraries\Forking::$_colorCLI in /var/www/nZEDb/nzedb/libraries/Forking.php on line 1027
[13-Sep-2016 11:56:43 America/Chicago] PHP Fatal error:  Cannot redeclare nzedb\libraries\Forking::$_colorCLI in /var/www/nZEDb/nzedb/libraries/Forking.php on line 1027
[13-Sep-2016 11:56:43 America/Chicago] PHP Fatal error:  Cannot redeclare nzedb\libraries\Forking::$_colorCLI in /var/www/nZEDb/nzedb/libraries/Forking.php on line 1027
[13-Sep-2016 11:56:43 America/Chicago] PHP Fatal error:  Cannot redeclare nzedb\libraries\Forking::$_colorCLI in /var/www/nZEDb/nzedb/libraries/Forking.php on line 1027
[13-Sep-2016 11:56:43 America/Chicago] PHP Fatal error:  Cannot redeclare nzedb\libraries\Forking::$_colorCLI in /var/www/nZEDb/nzedb/libraries/Forking.php on line 1027
[13-Sep-2016 11:56:44 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/Categorize.php on line 55

**Comment by niel** [comment] 2016-09-13 17:06
Pushed another commit, please try.

**Comment by dilbaggins** [comment] 2016-09-13 17:08
working now.  p.s. gotta love realtime break fix :)

**Comment by niel** [comment] 2016-09-13 17:09
@scottia are you still seeing:
PHP Fatal error: Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/Categorize.php on line 55 ?

**Comment by scottia** [comment] 2016-09-13 17:11
up and running bout 5 min. now.  

Yes I have 2 of these now :
[13-Sep-2016 12:07:41 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/Categorize.php on line 55
[13-Sep-2016 12:07:56 America/Chicago] PHP Fatal error:  Call to undefined method nzedb\db\DB::getSetting() in /var/www/nZEDb/nzedb/Categorize.php on line 55

**Comment by scottia** [comment] 2016-09-13 17:12
Had to stop it.  Log filling up with Line 55 errors from above.

**Comment by niel** [comment] 2016-09-13 17:13
OK, I'm in the process of converting all of our scripts to use a newer method of getting settings from the settings table. The Forking problem was caused by my misunderstanding how it worked. Not sure how the Categorize got out into dev, but I have that fixed in my working branch. I'll cherry-pick into dev to fix the issue.

**Comment by scottia** [comment] 2016-09-13 17:15
sounds good.  really appreciate you @niel

**Comment by dilbaggins** [comment] 2016-09-13 17:15
confirmed the categorize item as well.  you rule @niel . i think i see a donation in your future :)

**Comment by niel** [comment] 2016-09-13 17:16
Try now.

**Comment by dilbaggins** [comment] 2016-09-13 17:17
![image](https://cloud.githubusercontent.com/assets/3989347/18483957/6b1b9cb2-79b4-11e6-9307-00bbdad18cc8.png)

**Comment by scottia** [comment] 2016-09-13 17:20
Nope @niel 

That just blew it up 
http://pastebin.com/VHu76BFj

**Comment by scottia** [comment] 2016-09-13 19:08
no update to pull in Dev ?

**Comment by DariusIII** [comment] 2016-09-13 19:19
@niel just pushed some fixes.

**Comment by scottia** [comment] 2016-09-13 20:02
Working but have this showing up

[13-Sep-2016 14:55:46 America/Chicago] PHP Warning:  Error while sending QUERY packet. PID=59190 in /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php on line 403
[13-Sep-2016 14:55:46 America/Chicago] PHP Fatal error:  Uncaught exception 'lithium\data\model\QueryException' with message 'SELECT `Settings`.`value`, `Settings`.`hint` FROM `settings` AS `Settings` WHERE `Settings`.`name` = 'categorizeforeign' AND `Settings`.`subsection` = 'categorise' AND `Settings`.`section` = 'indexer';: MySQL server has gone away' in /var/www/nZEDb/libraries/lithium/data/source/Database.php:1591
Stack trace:
#0 /var/www/nZEDb/libraries/lithium/aop/Filters.php(229): lithium\data\source\Database->lithium\data\source{closure}(Array)
#1 /var/www/nZEDb/libraries/lithium/data/source/Database.php(1592): lithium\aop\Filters::run(Object(lithium\data\source\database\adapter\MySql), '_error', Array, Object(Closure))
#2 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(405): lithium\data\source\Database->_error('SELECT `Setting...')
#3 /var/www/nZEDb/libraries/lithium/aop/Filters.php(229): lithium\data\source\database\adapter\MySql->lithium\data\source\database\adapter{closure}(Array)
#4 /var/www/nZEDb/libraries/lithium/data/sour in /var/www/nZEDb/libraries/lithium/data/source/Database.php on line 1591

**Comment by niel** [comment] 2016-09-13 21:58
@scottia is that occuring frequently? 
It looks like a standard message for "MySQL server has gone away", just that it is wrapped up in more info than would previously be shown.

**Comment by scottia** [comment] 2016-09-13 22:01
I wouldn't say frequently.  I see it a couple times an hour.  I just started seeing it, which is why I reported it.

**Comment by scottia** [comment] 2016-09-13 22:32
I believe this can be closed unless @dilbaggins  is still having issues.  I have the unrar memory issues like others but i believe Kevin is looking into that.

Thanks for your help @niel !!  Appreciate it.

**Closed as completed** 2016-09-13 22:33 UTC

**Comment by kevinlekiller** [comment] 2016-09-13 22:36
Not looking into it, waiting for someone to supply bad rar samples then I'll send the information to the rarinfo maintainer.

**Comment by scottia** [comment] 2016-09-13 22:41
If there is an easy way to do that, I will.  I see PP rev up while pausing for like 5 to 6 minutes on a small file while my memory maxes out.  My presumption is the unrar is causing that but can't say for sure.  If you can tell me how to monitor and collect samples, I will provide some to the repo your tracking on.

**Comment by kevinlekiller** [comment] 2016-09-13 22:53
If you have the releaseid, you can download the NZB and download 1 rar file out of the NZB possibly, might be a simpler way, but can't think of one currently.

**Comment by scottia** [comment] 2016-09-13 23:01
If I catch it doing it, I will pull a couple and provide the rar

**Comment by kevinlekiller** [comment] 2016-09-13 23:02
Sounds good, thanks.
