### ISSUE TITLE
Theme not loading properly

### ISSUE THREAD

**Issue by josh4trunks** [nZEDb/nZEDb#2021] opened 2016-01-07 06:23 UTC
My nZEDb site doesn't seem to be loading its theme (Alpha) since pulling in the changes from master on January 4th, 2016.
I believe it might be related to my site being hosted at a webroot (https://www.jruehlig.com/nzedb)

From this screenshot, I think those links should have "/nzedb" in front of them.
![2](https://cloud.githubusercontent.com/assets/1018807/12163599/f2f86b58-b4c3-11e5-804f-5376c847090c.png)

My stack is FreeBSD - NGINX - PHP-FPM, but I assume that is unrelated because I haven't changed anything other than pulling in the update. Please tell me anything I can do to help debug/fix this issue. Thanks!

**Comment by niel** [comment] 2016-01-07 12:47
Currently we don't directly support non-standard configurations like this, anything outside a 'normal' setup is an exercise for the site admin. You should be able to fix this using 'aliases' in your site config file or rewrite rules.
We are discussing, in dev channel, whether we want to directly support this and how complicated it would make our code.

**Comment by josh4trunks** [comment] 2016-01-07 15:56
Ok, thanks for the reply. I didn't know webroots weren't supported as there's mention of this in INSTALL.txt dating back to newznab. This has been working fine for me for the last year though so I'll dig into the recent changes and see why the relative path is no longer being used.

To save me some time, do you know what "smarty.const.WWW_TOP" is supposed to have, and where it is being set? Thanks

**Comment by josh4trunks** [comment] 2016-01-07 16:22
This fixed the issue for me.

In https://github.com/nZEDb/nZEDb/blob/master/www/smarty.php#L58 change..
``define('WWW_THEMES', '/themes');``
to..
``define('WWW_THEMES', $www_top . '/themes');``

**Comment by niel** [comment] 2016-01-07 16:23
lol I was just writing a reply to you pointing out the WWW_THEMES constant.
I had an idea to possibly fix this, but yours is simpler. If it's that simple I will add it.

**Comment by josh4trunks** [comment] 2016-01-07 16:25
Awesome, I think the above change would fix it unless an admin really modified the way fines were layed out.

**Comment by niel** [comment] 2016-01-07 16:26
can you check that it doesn't screw up admin access? this was the problem I had during development.

**Comment by josh4trunks** [comment] 2016-01-07 16:31
Good catch, admin access is still unthemed (as it was before the change). But at least the webroot is being given, just the "/admin" part needs to be removed.

![screenshot from 2016-01-07 08-29-03](https://cloud.githubusercontent.com/assets/1018807/12175761/d5954fe0-b518-11e5-966b-9cba7814d320.png)

**Comment by niel** [comment] 2016-01-07 16:33
Yeah, that's not workable then.

**Comment by josh4trunks** [comment] 2016-01-07 16:33
Without the change, I am being served without "/nzedb/admin" so I see your point.
![screenshot from 2016-01-07 08-32-00](https://cloud.githubusercontent.com/assets/1018807/12175851/50c622a2-b519-11e5-87c7-d698577f8308.png)

**Comment by niel** [comment] 2016-01-07 16:37
The problem here is that WWW_TOP is set to /nzedb/admin so removing the admin isn't possible. Looks like I will have to investigate my original idea, if the dev's consensus is to support non-standard configurations.

**Comment by josh4trunks** [comment] 2016-01-07 16:38
Sounds good, thanks

**Comment by niel** [comment] 2016-01-07 16:47
BTW I just read INSTALL.txt and only see one mention of not working with web root. "set www\.htaccess RewriteBase to your virtual directory" Which pretty much echoes my own understanding, if you want to do it, it's up to the site admin to make it work. Note that comment only refers to Apache, there's no mention of what to do for nginx, but I'm sure it should be possible using its own syntax.

**Comment by josh4trunks** [comment] 2016-01-07 16:51
Yup, that note has been there since newznab days.
NGINX only requires the usual changes of running something in a webroot, and I'd assume most admins using NGINX should know how to write/edit an nginx config.

**Comment by niel** [comment] 2016-01-09 16:10
Have a fix for this in dev.

**Closed by niel** 2016-01-09 16:10 UTC
Labels: MASTER

**Comment by josh4trunks** [comment] 2016-01-09 16:18
thanks that was quick!

**Comment by niel** [comment] 2016-01-09 16:25
I was already investigating it before you created the issue ;-) Mostly I needed to know how widespread the issue is/was before investing time in it. No guarantees it will not break again in the future, as we're not  giving anything but the most basic support (i.e. trying not to break it, but main code needs take precedence) to this configuration.
