### ISSUE TITLE
New Install - Unable to update Site Settings / All blank

### ISSUE THREAD

**Issue by krypknot** [nZEDb/nZEDb#2104] opened 2016-04-12 01:57 UTC
### Expected behaviour

Default settings to be present in the majority of fields.  Fields, such as Title, can then be updated and saved.
### Actual behaviour

Most settings are blank.  Fields and options can be set, but when save is clicked the page results in all fields being blank.
### Steps to reproduce the behaviour

Install using Ubuntu guide / Using mariadb / Pulled latest dev / Follow additional instructions in ChangeLog (for composer)
Visit site and complete initial setup
In Admin UI click Site Settings / Edit Site - try and change the site's title and save it.

**Comment by niel** [comment] 2016-04-12 05:54
Composer is only in use for the dev branch. I suspect you should be using the 0.x stable branch.
The lack of setting is usually a sign that your database tables are not set up correctly, often caused by file permission issues.

**Comment by rcketscientist** [comment] 2016-04-12 10:27
I have the same issue.  I'm looking into it now.

**Comment by krypknot** [comment] 2016-04-12 14:47
Thanks neil.  I did ensure I installed it properly - it's for home use so a chmod 777 -R ./nZEDb    is fine for me and what I use.  The rest of the site appears to function normally (such as binaries.php will save headers in to the DB).  So I'm doubtful it's permissions.

However, looking at the settings table, it's obvious that something is not being setup properly - but only for that table.   Since I didn't receive any errors and it's the only table acting up - I'm suspecting it's not an environmental issue on my end...

**Comment by niel** [comment] 2016-04-12 19:17
Can you use SQL to access the DB (MySQL client, PHPMyAdmin, or similar). If so, would let me know what the contents look like - do NOT list the entire output, unless it does not contain your own keys (seems likely if you can't get the fields to display).

**Comment by rcketscientist** [comment] 2016-04-12 19:33
Do you just want to see those in settings table?  I'm having the same issue with settings.

**Comment by niel** [comment] 2016-04-12 19:40
Of course the settings table, the whole issue is about the settings.
However, I'd prefer to get them from @slypknot as this is his issue post.

**Comment by rcketscientist** [comment] 2016-04-12 19:51
[settings.pdf](https://github.com/nZEDb/nZEDb/files/215814/settings.pdf)

nzbpath was manually edited to try to move forward.  It still didn't work, but it also isn't clearing that setting either.

**Comment by slypknot** [comment] 2016-04-13 01:34
[mysql-query.txt](https://github.com/nZEDb/nZEDb/files/216261/mysql-query.txt)


I've attached a log of the query when I try to update the settings page in a few places - also my settings tbl.

**Comment by krypknot** [comment] 2016-04-13 01:37
I've attached a log of the query when I try to update the settings page in a few places - also my settings tbl.  
[mysql-query.log.txt](https://github.com/nZEDb/nZEDb/files/216262/mysql-query.txt)
[settings.table.pdf.zip](https://github.com/nZEDb/nZEDb/files/216267/settings.table.pdf.zip)

php --version
PHP 5.6.20-1+deb.sury.org~trusty+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by just-another-gituser** [comment] 2016-05-03 00:53
I have had this issue with three installs in a row, the latest one being done just now as the code has moved from RC to stable.

**Comment by niel** [comment] 2016-05-04 17:10
Fixed in dev and stable branch.

**Closed as completed by niel** 2016-05-04 17:10 UTC

**Comment by Wally73** [comment] 2016-05-05 09:23
@niel  you only pushed it to stable and latest-testing not into dev itself

**Comment by niel** [comment] 2016-05-05 14:16
Now in dev, too ;-)

**Comment by brando56894** [comment] 2016-05-12 07:04
I just installed this on Arch Linux and I'm having the same issue....

I'm using PHP v7 with php-fpm and nginx though.

[settings.pdf](https://github.com/nZEDb/nZEDb/files/260758/settings.pdf)

**Comment by Wally73** [comment] 2016-05-12 07:16
i think that php7 is your problem. just install 5.6.19 or 20

**Comment by niel** [comment] 2016-05-12 17:37
@brando56894  This was fixed, so it's likely a configuration/permissions problem.
If it's a new but similar problem, please create a new issue.
