### ISSUE TITLE
blank page on deployment

### ISSUE THREAD

**Issue by thejrose1984** [nZEDb/nZEDb#2222] opened 2016-07-25 01:36 UTC
### Expected behaviour

redirect to install page
### Actual behaviour

blank page
### Steps to reproduce the behaviour

`# cd /usr/local/www/nZEDb`
`# git pull`
`# composer update`
`# ./zed update`
`# pkg upgrade -y ; pkg clean -y ; pkg audit ; service nginx restart ; service php-fpm restart`
php error log = http://pastebin.com/92T9DHUf
nginx access log = http://pastebin.com/P7GQxUFb

**Comment by DariusIII** [comment] 2016-07-25 06:08
You have already raised the same issue, and @niel closed it as it is a duplicate of already solved issue in dev.

**Closed as completed by DariusIII** 2016-07-25 06:08 UTC
Labels: DUPLICATE

**Comment by thejrose1984** [comment] 2016-07-25 09:00
I opened a new ticket after acknowledging new items were pulled from repo. It's still an issue so I don't see how closing tickets when an issue hasn't been verified as resolved helps anyone.

**Comment by DariusIII** [comment] 2016-07-25 09:35
As you are on 0.x branch until it gets merged from dev you will not see any improvements.

https://github.com/nZEDb/nZEDb/issues/2214

**Comment by niel** [comment] 2016-07-25 15:42
I'll be creating a new RC version (Latest-testing branch) today, which will merge this and other changes in preparation for a new release next week.

**Comment by niel** [comment] 2016-07-25 21:44
v0.6.3-RC1 is available now.
git clone --branch Latest-testing https://github.com/nZEDb/nZEDb.git
and then run:
composer install
