### ISSUE TITLE
No XXX covers downloaded since a couple of weeks

### ISSUE THREAD

**Issue by Atmos01** [nZEDb/nZEDb#1927] opened 2015-10-27 08:04 UTC
I get allot of this lately:

![image](https://cloud.githubusercontent.com/assets/13801996/10752414/4a414f88-7c89-11e5-8472-5a89afcc3bb1.png)

It still finds covers but most of the new releases in XXX do not have one.. When i check the info sites i can see the covers.. Is this my installation or is this a new bug?

**Comment by Wally73** [comment] 2015-10-27 08:56
https://github.com/nZEDb/nZEDb/issues/1914

**Comment by Bart39** [comment] 2015-10-27 21:34
duplicate of #1914 closing

**Closed by Bart39** 2015-10-27 21:34 UTC
