### ISSUE TITLE
Anyone experiencing high load with latest master?

### ISSUE THREAD

**Issue by Fossil01** [nZEDb/nZEDb#1939] opened 2015-11-03 09:31 UTC
Just checking if I'm the only one. I run a fairly high traffic website so any bugs in the API for example cause high load for me.

Pulled latest master yesterday, ran the DB patches and the whole site became unresponsive, especially when trying to open the /browse page (caused 504 Gateway Time-Out). After that I had to restart MySQL and nginx to get it going again for 5 seconds. Even putting Redis in front of it did not work.

Reverted to a DB back-up and the previous master. Site runs OK again now.

**Comment by sebst3r** [comment] 2015-11-03 11:19
i also have poor performance since the latest master and reverted back

**Comment by Bart39** [comment] 2015-11-03 11:43
any php errors / debug in /resources/logs/nzedb.log ?

**Comment by lulunzb** [comment] 2015-11-04 10:27
I have a similar issue - browse on TV is terrible (ie over 2 minutes to open), I put it down to have over 500K of tv releases now in post process due to the tvrage changes.   Others are reasonably normal. 

This query seems to be the cause, interesting to see if this changed in the last release.

# Query_time: 159.732995  Lock_time: 0.000289  Rows_sent: 50  Rows_examined: 4173251  Rows_affected: 0
# Bytes_sent: 30060
SET timestamp=1446632694;
SELECT r.*,
                                        CONCAT(cp.title, ' > ', c.title) AS category_name,
                                        CONCAT(cp.id, ',', c.id) AS category_ids,
                                        COUNT(df.id) AS failed,
                                        g.name AS group_name,
                                        rn.id AS nfoid,
                                        re.releaseid AS reid,
                                        v.tvdb, v.trakt, v.tvrage, v.tvmaze, v.imdb, v.tmdb,
                                        tve.title, tve.firstaired
                                FROM releases r
                                STRAIGHT_JOIN groups g ON g.id = r.group_id
                                STRAIGHT_JOIN category c ON c.id = r.categoryid
                                INNER JOIN category cp ON cp.id = c.parentid
                                LEFT OUTER JOIN videos v ON r.videos_id = v.id
                                LEFT OUTER JOIN tv_episodes tve ON r.tv_episodes_id = tve.id
                                LEFT OUTER JOIN video_data re ON re.releaseid = r.id
                                LEFT OUTER JOIN release_nfos rn ON rn.releaseid = r.id
                                LEFT OUTER JOIN dnzb_failures df ON df.guid = r.guid
                                WHERE r.nzbstatus = 1
                                AND r.passwordstatus = 0
                                 AND ( r.categoryid IN (-99, 5010, 5020, 5030, 5040, 5050, 5060, 5070, 5080) OR 1=2 )   
                                GROUP BY r.id
                                ORDER BY postdate desc  LIMIT 50 OFFSET 0;

**Comment by lulunzb** [comment] 2015-11-04 10:35
and no errors of note in nzedb.log

**Comment by Bart39** [comment] 2015-11-04 11:08
this was fixed in dev and is currently in next-master - it's not made it to master yet
https://github.com/nZEDb/nZEDb/commit/1fdea4868a4c1a98a9985cd2e2d87c2cc372003c

**Comment by lulunzb** [comment] 2015-11-04 11:24
Oh awesome - confirmed fixed after applying the change.

**Closed** 2015-11-04 14:33 UTC
