### ISSUE TITLE
[bug] WEB-DL shows as option in My TV shows when not used as a category

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2110] opened 2016-04-13 20:03 UTC
Choosing to not opt-in to "Categorize WEB-DL"  still shows WEB-DL as an option in /myshows/add/
### Expected behaviour

No trace of WEB-DL when it's never been used as a category
### Actual behaviour

 Remanence of WEB-DL in editing My TV Shows 
### Steps to reproduce the behaviour

Start a fresh install. Do not opt-in to  "Categorize WEB-DL".  Add a series from /series and you are displayed with the quality page which shows the option for WEB-DL.

**Comment by niel** [comment] 2016-04-15 01:57
This isn't actually a bug, as it has always been this way and was intended to be so I believe.
Changed it to a [REQ] and I'll put it on our back burner for consideration.

**Comment by b3rs3rk** [comment] 2016-05-11 01:39
Tested fixed in dev branch.

**Closed as completed by b3rs3rk** 2016-05-11 01:39 UTC
Labels: ENHANCEMENT, FRONTEND, REQUEST, TESTED
