### ISSUE TITLE
fresh install does not import table data

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2167] opened 2016-06-08 09:07 UTC
expected behaviour from the installer:
category_regexes and categories and other table data is imported into the database for release processing to work.

current behaviour:
all tables are empty

to reproduce:
do a fresh install through composer

**Comment by Wally73** [comment] 2016-06-08 09:37
did you do 

`GRANT FILE ON *.* TO 'YourMySQLUsername'@'YourMySQLServerHostName';`

**Comment by OliverLeitner** [comment] 2016-06-08 10:07
yes

**Comment by OliverLeitner** [comment] 2016-06-08 10:07
and all other tables are working, its only affecting category and categories_regex, the tsv files seem to have errors in them. in dev and in stable. just try it. please

**Comment by b3rs3rk** [comment] 2016-06-08 19:52
The TSV files do not have errors, GitHub just can't parse them correctly for whatever reason.  There is nothing wrong with category_regex is it wasn't changed but probably should be as a result of the sweeping changes made by @niel in his never ending quest for perfection.  The issue is that the category table was changed to categories and the installer preg_matches the table name from the TSV to load.  The TSV file for categories was not changed so the installer tried to insert all the data into category not categories like it should.

Fixed in dev: 0eb75f39645002badfcc8676814ec8acda64b0f2
Cherry-picked to 0.x: ae0357fa25a705eda42f2cb9f5d125a3773980bb

**Closed as completed by b3rs3rk** 2016-06-08 19:52 UTC
