### ISSUE TITLE
HTTP ERROR 500 at Login

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2314] opened 2016-11-19 16:23 UTC
###Expected behaviour
I get the login page, and can login

###Actual behaviour
HTTP Error 500 (Log snippet below)

```
[19-Nov-2016 17:20:34 Europe/Berlin] PHP Fatal error:  Uncaught Exception: Unable to fetch setting from Db! in D:\www\nZEDb\app\models\Settings.php:205
Stack trace:
#0 D:\www\nZEDb\nzedb\Captcha.php(200): app\models\Settings::value('APIs.recaptcha....')
#1 D:\www\nZEDb\nzedb\Captcha.php(112): nzedb\Captcha->_bootstrapCaptcha()
#2 D:\www\nZEDb\nzedb\Captcha.php(87): nzedb\Captcha->shouldDisplay()
#3 D:\www\nZEDb\www\pages\login.php(8): nzedb\Captcha->__construct(Object(Page))
#4 D:\www\nZEDb\www\index.php(76): require_once('D:\\www\\nZEDb\\ww...')
#5 {main}
  thrown in D:\www\nZEDb\app\models\Settings.php on line 205
```

###Steps to reproduce the behaviour
Try to login

**Comment by samwiseg0** [comment] 2016-11-21 04:15
I had an issue where the settings table was messed up. Have you tried to see the data in the table and fix the broken records?

I think it has to do with the latest update.

**Comment by niel** [comment] 2016-11-21 13:30
Duplicate of https://github.com/nZEDb/nZEDb/issues/2312

**Closed as completed by niel** 2016-11-21 13:30 UTC
Labels: DUPLICATE
