### ISSUE TITLE
Default Template Issues

### ISSUE THREAD

**Issue by Loopher** [nZEDb/nZEDb#2011] opened 2015-12-31 05:51 UTC
Dev - Latest build.

When viewing the Movies, Audio or Console sections under the Covers view and you select a post, the page generates an error.  The errors seem to differ depending on the category you are viewing.

Under the Movies section while viewing the Covers, when you select a posting you are presented with an error message - Server error 500.   The URL it has in the URL line is: https://localhost/movies/?imdb=1226753

Under the Audio section while viewing the covers, you are presented with a 403 Forbidden.
Url displayed on the browser is:  https://localhost/details/

Also, I wanted to point out that when I selected another template like Gamma, this works properly.  It appears to be broken on the Default, Light, Simple and Shared templates.

**Comment by Wally73** [comment] 2015-12-31 06:19
yep on default theme that is indeed the case (also on dev)

but Alpha works fine so why do you use default?? (that one is ancient)

**Comment by Loopher** [comment] 2015-12-31 07:34
Well, I like the default template and thought it would be updated as the software was being developed.  If this is no longer the case, I will swap over to the Gamma template and adjust my logo, banner, etc...  Just need to know which direction to head.  :+1:

**Comment by niel** [comment] 2016-01-01 00:12
I'll look into this.

**Comment by niel** [comment] 2016-01-04 10:11
Can you give me more details on *exactly* how to reproduce the error. I must be misunderstanding something as I don't see any problems.

**Comment by niel** [comment] 2016-01-04 10:14
BTW I agree that Default should be kept up to date and I'm beginning to do some work that will take care of that.

**Comment by niel** [comment] 2016-01-04 13:39
Would you check latest dev branch. You should find the film and console title links now work. Let me know if the audio is as I don't have any entries to test with.

**Comment by Loopher** [comment] 2016-01-04 22:38
Everything appears to be functioning properly now.  Thank you guys for the updates.   :+1:

**Comment by Loopher** [comment] 2016-01-04 22:45
Correction, the Audio section is still not providing the details of an album when viewing under cover mode.  When I click on the CD/Album cover picture, I get a 403 Forbidden.  The URL that is being presented is http://localhost/details/.  Everything else appears to be working great though.

**Comment by kaibosh** [comment] 2016-01-07 11:15
One other small default theme issue since the last master update, the movie view page comes up blank. i.e. http://site/movies/?imdb=xxxxxxx
Still working fine with other themes

**Comment by niel** [comment] 2016-01-07 12:32
@kaibosh this issue is for the dev branch. If you mean clicking the film title brings up a status error, then that is fixed in dev.
If it is another problem, please create a separate issue mentioning it is on master.

**Comment by kaibosh** [comment] 2016-01-07 13:08
Oh ok, yeah that bug is in next-master. Getting a blank page, could just be the client (firefox). Will create new issue as needed.

**Closed** 2016-02-24 01:25 UTC
