### ISSUE TITLE
Cannot import nzbs from browser

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#2284] opened 2016-10-12 12:51 UTC
### Expected behaviour

Import NZB from browser and it imports
### Actual behaviour

Get http error 500

in apache2 error log get this message:
[Wed Oct 12 08:26:33 2016] [error] [client 192.168.1.1] PHP Fatal error:  Uncaught exception 'lithium\core\ConfigException' with message 'The data connection `default` is not configured for model `app\\models\\Settings`.' in /var/www/myserver.com/htdocs/nZEDb/libraries/lithium/data/Model.php:1479\nStack trace:\n#0 /var/www/myserver.com/htdocs/nZEDb/libraries/lithium/data/Model.php(674): lithium\data\Model::connection()\n#1 /var/www/myserver.com/htdocs/nZEDb/app/models/Settings.php(58): app\models\Settings::lithium\data\{closure}(Array)\n#2 /var/www/myserver.com/htdocs/nZEDb/libraries/lithium/data/Model.php(694): app\models\Settings::app\models\{closure}(Array, Object(Closure))\n#3 /var/www/myserver.com/htdocs/nZEDb/libraries/lithium/aop/Filters.php(229): app\models\Settings::lithium\data\{closure}(Array)\n#4 /var/www/myserver.com/htdocs/nZEDb/libraries/lithium/data/Model.php(697): lithium\aop\Filters::run('app\\models\\Sett...', 'find', Array, Object(Closure))\n#5 /var/www/myserver.com/htdocs/nZEDb/app/models/Settings.php(81): lithium\data\Model::fi in /var/www/myserver.com/htdocs/nZEDb/libraries/lithium/data/Model.php on line 1479, referer: http://myserver.com/admin/nzb-import.php

I could not find any php errors associated with this.
I just updated this AM on 0.x branch. I don't know if that has anything to do with it because I haven't tried importing from the website in a while. May just be a coincidence.
### Steps to reproduce the behaviour

Try to import nzb from browser

**Comment by DariusIII** [comment] 2016-10-12 12:58
Duplicate of issue #2280

**Closed as completed by DariusIII** 2016-10-12 12:58 UTC
Labels: DUPLICATE
