### ISSUE TITLE
MAJOR Bug - update_releases.php not deleting

### ISSUE THREAD

**Issue by davidritterhouse** [nZEDb/nZEDb#1842] opened 2015-08-23 15:03 UTC
This is a major bug.  update_releases.php is NOT deleting collections or binaries from the tables.  I have tried running manually, screen and tmux.  Same issue. Just a constant loop.

It just loops over and over. 

![error](https://cloud.githubusercontent.com/assets/13871539/9428739/7fada2e2-4986-11e5-8dfe-514e849c7164.png)

**Comment by Bart39** [comment] 2015-08-23 15:07
It is not a major bug as it is not affecting anyone else but you (as far as we know at the moment)
Also this is a duplicate of your other issue

**Closed by Bart39** 2015-08-23 15:07 UTC

**Comment by davidritterhouse** [comment] 2015-08-23 15:13
This is a brand new install from a VM.  I felt this was a new issue due to the update_releases.php.  Sorry for the duplicate submission.
